name: Trivy Container Image Scan

on:
  workflow_dispatch:

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t insecure-image:latest .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: insecure-image:latest
          format: table
          severity: CRITICAL,HIGH
          ignore-unfixed: true